const express = require('express');
const postsController = require('../controllers/posts');
const checkAuth = require('../middelware/check-auth');
const extrackFiles = require('../middelware/file');
const router = express.Router();
router.get("", postsController.getList);
router.get("/:id",checkAuth, postsController.getDetails);
router.post("",checkAuth, extrackFiles ,postsController.insert);
router.put("/:id",checkAuth, extrackFiles, postsController.update);
router.delete("/:id",checkAuth, postsController.delete);
module.exports = router;
